name: Build Linux Desktop App

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: latest

      - name: Install nodejs dependencies for webui
        run: make install-webui

      - name: Test webui
        run: make test-webui

      - name: Build webui
        run: make build-webui

      - name: Check webui build is in assets/webui
        run: make check-build-webui

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install build dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y clang g++ build-essential cmake \
                             ninja-build libgtk-3-dev pkg-config liblzma-dev

      - name: Install + Test + Build  flutter application
        run: |
          make install-flutter
          make test
          flutter build linux

      - name: Upload build artifact
        if: env.ACT != 'true'
        uses: actions/upload-artifact@v5
        with:
          name: linux-build
          path: build/linux/x64/release/bundle/
